resilience4j:
  circuitbreaker:
    instances:
      reserva-api:
        failureRateThreshold: 50
        minimumNumberOfCalls: 10
        slidingWindowSize: 20
        waitDurationInOpenState: 60s
  retry:
    instances:
      reserva-api:
        maxAttempts: 3
        waitDuration: 1s

# Configuração de Cache e Redis
spring:
  cache:
    type: redis
    redis:
      timeout: 10000ms
  data:
    redis:
      host: localhost
      port: 6379
