server:
  port: 8080
spring:
  application:
    name: reserva-evento-service
  datasource:
    url: jdbc:h2:mem:reservadb;DB_CLOSE_DELAY=-1
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
  # Configuração de Cache e Redis
  cache:
    type: redis
    redis:
      timeout: 10000ms
  data:
    redis:
      host: localhost
      port: 6379

kafka:
  bootstrap-servers: localhost:9092
  producer:
    key-serializer: org.apache.kafka.common.serialization.StringSerializer
    value-serializer: org.apache.kafka.common.serialization.StringSerializer
    acks: all
    retries: 3
  consumer:
    group-id: reservas-group
    auto-offset-reset: earliest
    key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
  listener:
    missing-topics-fatal: false
