  server:
  port: 8080
  spring:
    application:
    name: reserva-evento-service
  datasource:
    url: jdbc:h2:mem:reservadb;DB_CLOSE_DELAY=-1
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
    ddl-auto: update
    show-sql: true
  kafka:
    bootstrap-servers: localhost:9092 # Endereço do seu servidor Kafka
    # Configurações do Produtor (para enviar mensagens)
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      acks: all
      retries: 3

    # Configurações do Consumidor (para receber mensagens)
    consumer:
      group-id: reservas-group # Identificador para este grupo de consumidores
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

    # Configurações do Listener (para o @KafkaListener)
    listener:
      missing-topics-fatal: false # Permite que a aplicação inicie mesmo se o tópico não existir

